- hosts: node
  become: true
  tasks:
    - name: Delete old deployment
      ansible.builtin.command: >
        ssh -o StrictHostKeyChecking=no ubuntu@172.31.82.95 
        "KUBECONFIG=/home/ubuntu/.kube/config kubectl delete -f /home/ubuntu/Deployment.yml"
      ignore_errors: yes  # Ignore errors if the resource doesn't exist

    - name: Delete old service
      ansible.builtin.command: >
        ssh -o StrictHostKeyChecking=no ubuntu@172.31.82.95 
        "KUBECONFIG=/home/ubuntu/.kube/config kubectl delete -f /home/ubuntu/Service.yml"
      ignore_errors: yes

    - name: Apply new deployment
      ansible.builtin.command: >
        ssh -o StrictHostKeyChecking=no ubuntu@172.31.82.95 
        "KUBECONFIG=/home/ubuntu/.kube/config kubectl apply -f /home/ubuntu/Deployment.yml"

    - name: Apply new service
      ansible.builtin.command: >
        ssh -o StrictHostKeyChecking=no ubuntu@172.31.82.95 
        "KUBECONFIG=/home/ubuntu/.kube/config kubectl apply -f /home/ubuntu/Service.yml"
