- hosts: node
  become: true
  tasks:
    - name: Ensure Minikube environment is set
      shell: |
        eval $(minikube docker-env)
        echo "Minikube environment initialized."

    - name: Delete old deployment (if exists)
      shell: |
        kubectl delete -f /home/ubuntu/Deployment.yml --ignore-not-found=true
      args:
        executable: /bin/bash

    - name: Delete old service (if exists)
      shell: |
        kubectl delete -f /home/ubuntu/Service.yml --ignore-not-found=true
      args:
        executable: /bin/bash

    - name: Apply new deployment
      shell: |
        kubectl apply -f /home/ubuntu/Deployment.yml
      args:
        executable: /bin/bash

    - name: Apply new service
      shell: |
        kubectl apply -f /home/ubuntu/Service.yml
      args:
        executable: /bin/bash

